input CreateManagerInput {
  email: String!
  name: String!
  password: String!
}

input UpdateManagerInput {
  email: String
  name: String
}

type Manager {
  createdAt: DateTime!
  email: String!
  id: ID!
  name: String!
  userSessions: [UserSession]
  userId: ID!
  user: User!
  updatedAt: DateTime
}

extend type Mutation {
  createManager(input: CreateManagerInput!): Manager! @user
  deleteManager(id: ID!): Manager! @user
  updateManager(id: ID!, input: UpdateManagerInput!): Manager! @user
}
