input CreateManagerInput {
  email: String!
  name: String!
  password: String!
}

input UpdateManagerInput {
  email: String!
  name: String!
}

type Manager implements Node {
  createdAt: DateTime!
  databaseId: UUID!
  email: String!
  id: ID!
  name: String!
  updatedAt: DateTime!
  # user: User!
  userId: ID!
  userSessions: [UserSession!]!
}

extend type Mutation {
  createManager (input: CreateManagerInput!): Manager! @user
  deleteManager (id: ID!): Manager! @user
  updateManager (id: ID!, input: UpdateManagerInput!): Manager! @user
}
